# Generated by Django 5.2.1 on 2025-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0010_comment_user_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
